<?php
/**
 * @file
 * This module integrates tops features with Drupal 8
 */
use Tops\Drupal\TViewModel;

/**
 * Implements hook_help().
 */
$drupalAutoloader = require_once(__DIR__.'/../../lib/Tops/start/autoload.php');
require_once(__DIR__.'/../../lib/Tops/start/init.php');
// require_once(__DIR__.'/../../lib/App/start/init.php');


function tops_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match)
{
    return 'Help from tops';
}

/**
 * Implements hook_preprocess().
 */
function tops_preprocess(&$variables, $hook)
{
    if ($hook == 'html') {
        $vm = TViewModel::getVmName();
        $variables['view_model_name'] = $vm;
    }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function tops_preprocess_HOOK(&$variables)
{
}
