<?php
/**
 * @file
 * This module integrates tops features with Drupal 8
 */
use Tops\Drupal\TViewModel;
use Tops\sys\TSession;

/**
 * Implements hook_help().
 */
$drupalAutoloader = require_once(__DIR__.'/../../lib/Tops/start/autoload.php');
require_once(__DIR__.'/../../lib/Tops/start/init.php');
// require_once(__DIR__.'/../../lib/App/start/init.php');


/**
 * Implements hook_preprocess().
 */
function tops_preprocess(&$variables, $hook)
{
    if ($hook == 'html') {
        $vmPath = TViewModel::getVmPath();
        $hasVm = (!empty($vmPath));
        $variables['peanut_viewmodel'] = $hasVm;
        $variables['peanut_viewmodel_src'] = $vmPath;
        $variables['tops_js_debug'] =  \Tops\sys\TTracer::JsDebuggingOn();
    }
}


/**
 * Implements hook_preprocess_HOOK().
 */
/**
 * Implements hook_page_attachments().
 */
function tops_page_attachments(array &$attachments)
{
    if (TViewModel::isVmPage()) {
        if (\Tops\sys\TTracer::JsDebuggingOn()) {
            $attachments['#attached']['library'][] = 'tops/peanut.debug';
        }
        else {
            $attachments['#attached']['library'][] = 'tops/peanut.app';
        }
    }
}
